name: 's4y-a11y'
description: 'Provide a description here'
author: 'Gowtham G'
inputs:
  GITHUB_TOKEN: # change this
    required: true
    description: 'Access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
